fof(c_0_47,conjecture,![A]:![B]:(theorem(or(A,B))|~theorem(or(B,or(A,B))))).
cnf(rule_2,axiom,(theorem(A)|~axiom(or(not(B),A))|~theorem(B))).
cnf(axiom_1_5,axiom,axiom(or(not(or(A,or(B,C))),or(B,or(A,C))))).
cnf(axiom_1_3,axiom,axiom(or(not(A),or(B,A)))).
cnf(axiom_1_4,axiom,axiom(or(not(or(A,B)),or(B,A)))).
cnf(rule_3,axiom,(theorem(or(not(A),B))|~axiom(or(not(A),C))|~theorem(or(not(C),B)))).
cnf(rule_1,axiom,(theorem(A)|~axiom(A))).
cnf(axiom_1_2,axiom,axiom(or(not(or(A,A)),A))).
cnf(axiom_1_6,axiom,axiom(or(not(or(not(A),B)),or(not(or(C,A)),or(C,B))))).
cnf(c_0_9,axiom,(theorem(A)|~axiom(or(not(B),A))|~theorem(B))).
cnf(c_0_10,axiom,axiom(or(not(or(A,or(B,C))),or(B,or(A,C))))).
cnf(c_0_11,axiom,axiom(or(not(A),or(B,A)))).
cnf(c_0_12,axiom,axiom(or(not(or(A,B)),or(B,A)))).
cnf(c_0_19,axiom,(theorem(or(not(A),B))|~axiom(or(not(A),C))|~theorem(or(not(C),B)))).
cnf(c_0_20,axiom,(theorem(A)|~axiom(A))).
cnf(c_0_21,axiom,axiom(or(not(or(A,A)),A))).
cnf(c_0_28,axiom,axiom(or(not(or(not(A),B)),or(not(or(C,A)),or(C,B))))).
