fof(c_0_19,conjecture,![A]:axiom(or(not(or(A,A)),A))).
cnf(rule_2,axiom,(theorem(A)|~theorem(implies(B,A))|~theorem(B))).
cnf(implies_definition,axiom,implies(A,B)=or(not(A),B)).
cnf(rule_1,axiom,(theorem(A)|~axiom(A))).
cnf(axiom_1_5,axiom,axiom(implies(or(A,or(B,C)),or(B,or(A,C))))).
cnf(axiom_1_2,axiom,axiom(implies(or(A,A),A))).
cnf(axiom_1_3,axiom,axiom(implies(A,or(B,A)))).
cnf(c_0_7,axiom,(theorem(A)|~theorem(implies(B,A))|~theorem(B))).
cnf(c_0_8,axiom,implies(A,B)=or(not(A),B)).
cnf(c_0_10,axiom,(theorem(A)|~axiom(A))).
cnf(c_0_11,axiom,axiom(implies(or(A,or(B,C)),or(B,or(A,C))))).
cnf(c_0_12,axiom,axiom(implies(or(A,A),A))).
cnf(c_0_21,axiom,axiom(implies(A,or(B,A)))).
