fof(c_0_30,conjecture,![A]:![B]:![C]:(theorem(or(not(A),or(B,C)))|~axiom(or(not(A),B)))).
cnf(rule_3,axiom,(theorem(or(not(A),B))|~axiom(or(not(A),C))|~theorem(or(not(C),B)))).
cnf(rule_1,axiom,(theorem(A)|~axiom(A))).
cnf(axiom_1_3,axiom,axiom(or(not(A),or(B,A)))).
cnf(axiom_1_4,axiom,axiom(or(not(or(A,B)),or(B,A)))).
cnf(rule_2,axiom,(theorem(A)|~axiom(or(not(B),A))|~theorem(B))).
cnf(axiom_1_5,axiom,axiom(or(not(or(A,or(B,C))),or(B,or(A,C))))).
cnf(axiom_1_2,axiom,axiom(or(not(or(A,A)),A))).
cnf(axiom_1_6,axiom,axiom(or(not(or(not(A),B)),or(not(or(C,A)),or(C,B))))).
cnf(c_0_9,axiom,(theorem(or(not(A),B))|~axiom(or(not(A),C))|~theorem(or(not(C),B)))).
cnf(c_0_10,axiom,(theorem(A)|~axiom(A))).
cnf(c_0_13,axiom,axiom(or(not(A),or(B,A)))).
cnf(c_0_16,axiom,axiom(or(not(or(A,B)),or(B,A)))).
cnf(c_0_17,axiom,(theorem(A)|~axiom(or(not(B),A))|~theorem(B))).
cnf(c_0_18,axiom,axiom(or(not(or(A,or(B,C))),or(B,or(A,C))))).
cnf(c_0_21,axiom,axiom(or(not(or(A,A)),A))).
cnf(c_0_24,axiom,axiom(or(not(or(not(A),B)),or(not(or(C,A)),or(C,B))))).
