fof(c_0_23,conjecture,![A]:![B]:![C]:![D]:(is_a_theorem(implies(implies(A,B),C))|~is_a_theorem(implies(implies(A,D),C))|~is_a_theorem(implies(B,D)))).
cnf(condensed_detachment,axiom,(is_a_theorem(A)|~is_a_theorem(implies(B,A))|~is_a_theorem(B))).
cnf(cn_21,axiom,is_a_theorem(implies(implies(A,implies(B,C)),implies(B,implies(A,C))))).
cnf(cn_22,axiom,is_a_theorem(implies(implies(A,B),implies(implies(C,A),implies(C,B))))).
cnf(cn_54,axiom,is_a_theorem(implies(implies(A,B),implies(implies(not(A),B),B)))).
cnf(cn_18,axiom,is_a_theorem(implies(A,implies(B,A)))).
cnf(cn_3,axiom,is_a_theorem(implies(A,implies(not(A),B)))).
cnf(c_0_7,axiom,(is_a_theorem(A)|~is_a_theorem(implies(B,A))|~is_a_theorem(B))).
cnf(c_0_8,axiom,is_a_theorem(implies(implies(A,implies(B,C)),implies(B,implies(A,C))))).
cnf(c_0_9,axiom,is_a_theorem(implies(implies(A,B),implies(implies(C,A),implies(C,B))))).
cnf(c_0_12,axiom,is_a_theorem(implies(implies(A,B),implies(implies(not(A),B),B)))).
cnf(c_0_18,axiom,is_a_theorem(implies(A,implies(B,A)))).
cnf(c_0_25,axiom,is_a_theorem(implies(A,implies(not(A),B)))).
