fof(c_0_17,conjecture,![A]:![B]:is_a_theorem(implies(not(A),implies(A,B)))).
cnf(condensed_detachment,axiom,(is_a_theorem(A)|~is_a_theorem(implies(B,A))|~is_a_theorem(B))).
cnf(cn_21,axiom,is_a_theorem(implies(implies(A,implies(B,C)),implies(B,implies(A,C))))).
cnf(cn_54,axiom,is_a_theorem(implies(implies(A,B),implies(implies(not(A),B),B)))).
cnf(cn_3,axiom,is_a_theorem(implies(A,implies(not(A),B)))).
cnf(c_0_5,axiom,(is_a_theorem(A)|~is_a_theorem(implies(B,A))|~is_a_theorem(B))).
cnf(c_0_6,axiom,is_a_theorem(implies(implies(A,implies(B,C)),implies(B,implies(A,C))))).
cnf(c_0_9,axiom,is_a_theorem(implies(implies(A,B),implies(implies(not(A),B),B)))).
cnf(c_0_12,axiom,is_a_theorem(implies(A,implies(not(A),B)))).
