fof(c_0_17,conjecture,![A]:![B]:![C]:(is_a_theorem(implies(A,B))|~is_a_theorem(C)|~is_a_theorem(implies(C,B)))).
cnf(condensed_detachment,axiom,(is_a_theorem(A)|~is_a_theorem(implies(B,A))|~is_a_theorem(B))).
cnf(mv2,axiom,is_a_theorem(implies(implies(A,B),implies(implies(B,C),implies(A,C))))).
cnf(mv1,axiom,is_a_theorem(implies(A,implies(B,A)))).
cnf(mv3,axiom,is_a_theorem(implies(implies(implies(A,B),B),implies(implies(B,A),A)))).
cnf(mv5,axiom,is_a_theorem(implies(implies(implies(A,B),implies(B,A)),implies(B,A)))).
cnf(c_0_6,axiom,(is_a_theorem(A)|~is_a_theorem(implies(B,A))|~is_a_theorem(B))).
cnf(c_0_7,axiom,is_a_theorem(implies(implies(A,B),implies(implies(B,C),implies(A,C))))).
cnf(c_0_11,axiom,is_a_theorem(implies(A,implies(B,A)))).
cnf(c_0_14,axiom,is_a_theorem(implies(implies(implies(A,B),B),implies(implies(B,A),A)))).
cnf(c_0_33,axiom,is_a_theorem(implies(implies(implies(A,B),implies(B,A)),implies(B,A)))).
