fof(c_0_32,conjecture,![A]:is_a_theorem(implies(A,not(not(A))))).
cnf(transitivity,axiom,(is_a_theorem(implies(A,B))|~is_a_theorem(implies(A,C))|~is_a_theorem(implies(C,B)))).
cnf(cn_49,axiom,is_a_theorem(implies(implies(not(A),not(B)),implies(B,A)))).
cnf(condensed_detachment,axiom,(is_a_theorem(A)|~is_a_theorem(implies(B,A))|~is_a_theorem(B))).
cnf(cn_35,axiom,is_a_theorem(implies(implies(A,implies(B,C)),implies(implies(A,B),implies(A,C))))).
cnf(cn_18,axiom,is_a_theorem(implies(A,implies(B,A)))).
cnf(c_0_6,axiom,(is_a_theorem(implies(A,B))|~is_a_theorem(implies(A,C))|~is_a_theorem(implies(C,B)))).
cnf(c_0_7,axiom,is_a_theorem(implies(implies(not(A),not(B)),implies(B,A)))).
cnf(c_0_8,axiom,(is_a_theorem(A)|~is_a_theorem(implies(B,A))|~is_a_theorem(B))).
cnf(c_0_9,axiom,is_a_theorem(implies(implies(A,implies(B,C)),implies(implies(A,B),implies(A,C))))).
cnf(c_0_12,axiom,is_a_theorem(implies(A,implies(B,A)))).
