fof(c_0_10,conjecture,![A]:![B]:![C]:![D]:![E]:(c_Type_Otyping(A,hAPP(hAPP(c_Lambda_OdB_OApp,B),C),D)|~c_Type_Otyping(A,C,E)|~c_Type_Otyping(A,B,hAPP(hAPP(c_Type_Otype_OFun,E),D)))).
cnf(cls_typing_OVar_0,axiom,c_Type_Otyping(A,c_Lambda_OdB_OVar(B),hAPP(A,B))).
cnf(cls_shift__eq_0,axiom,hAPP(c_Type_Oshift(A,B,C,D),B)=C).
cnf(cls_typing_OApp_0,axiom,(c_Type_Otyping(A,hAPP(hAPP(c_Lambda_OdB_OApp,B),C),D)|~c_Type_Otyping(A,C,E)|~c_Type_Otyping(A,B,hAPP(hAPP(c_Type_Otype_OFun,E),D)))).
cnf(cls_CHAINED_0,axiom,c_Type_Otyping(c_Type_Oshift(v_ea____,c_HOL_Ozero__class_Ozero(tc_nat),hAPP(hAPP(c_Type_Otype_OFun,v_Ta____),v_U____),tc_Type_Otype),c_Lambda_Olift(v_ta____,c_HOL_Ozero__class_Ozero(tc_nat)),v_Ta____)).
cnf(c_0_5,axiom,c_Type_Otyping(A,c_Lambda_OdB_OVar(B),hAPP(A,B))).
cnf(c_0_6,axiom,hAPP(c_Type_Oshift(A,B,C,D),B)=C).
cnf(c_0_7,axiom,(c_Type_Otyping(A,hAPP(hAPP(c_Lambda_OdB_OApp,B),C),D)|~c_Type_Otyping(A,C,E)|~c_Type_Otyping(A,B,hAPP(hAPP(c_Type_Otype_OFun,E),D)))).
cnf(c_0_12,axiom,c_Type_Otyping(c_Type_Oshift(v_ea____,c_HOL_Ozero__class_Ozero(tc_nat),hAPP(hAPP(c_Type_Otype_OFun,v_Ta____),v_U____),tc_Type_Otype),c_Lambda_Olift(v_ta____,c_HOL_Ozero__class_Ozero(tc_nat)),v_Ta____)).
