fof(c_0_23,conjecture,![A]:(theorem(A)|~axiom(A))).
cnf(rule_2,axiom,(theorem(A)|~axiom(or(not(B),A))|~theorem(B))).
cnf(axiom_1_6,axiom,axiom(or(not(or(not(A),B)),or(not(or(C,A)),or(C,B))))).
cnf(rule_3,axiom,(theorem(or(not(A),B))|~axiom(or(not(A),C))|~theorem(or(not(C),B)))).
cnf(axiom_1_5,axiom,axiom(or(not(or(A,or(B,C))),or(B,or(A,C))))).
cnf(rule_1,axiom,(theorem(A)|~axiom(A))).
cnf(axiom_1_2,axiom,axiom(or(not(or(A,A)),A))).
cnf(c_0_7,axiom,(theorem(A)|~axiom(or(not(B),A))|~theorem(B))).
cnf(c_0_8,axiom,axiom(or(not(or(not(A),B)),or(not(or(C,A)),or(C,B))))).
cnf(c_0_9,axiom,(theorem(or(not(A),B))|~axiom(or(not(A),C))|~theorem(or(not(C),B)))).
cnf(c_0_14,axiom,axiom(or(not(or(A,or(B,C))),or(B,or(A,C))))).
cnf(c_0_20,axiom,(theorem(A)|~axiom(A))).
cnf(c_0_21,axiom,axiom(or(not(or(A,A)),A))).
