fof(c_0_14,conjecture,![A]:![B]:c_Type_Otyping(A,c_Lambda_OdB_OVar(B),hAPP(A,B))).
cnf(cls_App_0,axiom,(c_Type_Otyping(A,hAPP(hAPP(c_Lambda_OdB_OApp,B),C),D)|~c_Type_Otyping(A,C,E)|~c_Type_Otyping(A,B,hAPP(hAPP(c_Type_Otype_OFun,E),D)))).
cnf(cls_T_0,axiom,v_T____=hAPP(hAPP(c_Type_Otype_OFun,v_T_H_H____),c_List_Ofoldr(c_Type_Otype_OFun,v_Ts____,v_T_H____,tc_Type_Otype,tc_Type_Otype))).
cnf(cls_typing_OVar_0,axiom,c_Type_Otyping(A,c_Lambda_OdB_OVar(B),hAPP(A,B))).
cnf(cls_shift__eq_0,axiom,hAPP(c_Type_Oshift(A,B,C,D),B)=C).
cnf(cls_lift__type_0,axiom,(c_Type_Otyping(c_Type_Oshift(A,B,C,tc_Type_Otype),c_Lambda_Olift(D,B),E)|~c_Type_Otyping(A,D,E))).
cnf(cls_uT_0,axiom,c_Type_Otyping(v_e____,v_u____,v_T____)).
cnf(c_0_7,axiom,(c_Type_Otyping(A,hAPP(hAPP(c_Lambda_OdB_OApp,B),C),D)|~c_Type_Otyping(A,C,E)|~c_Type_Otyping(A,B,hAPP(hAPP(c_Type_Otype_OFun,E),D)))).
cnf(c_0_8,axiom,v_T____=hAPP(hAPP(c_Type_Otype_OFun,v_T_H_H____),c_List_Ofoldr(c_Type_Otype_OFun,v_Ts____,v_T_H____,tc_Type_Otype,tc_Type_Otype))).
cnf(c_0_9,axiom,c_Type_Otyping(A,c_Lambda_OdB_OVar(B),hAPP(A,B))).
cnf(c_0_10,axiom,hAPP(c_Type_Oshift(A,B,C,D),B)=C).
cnf(c_0_19,axiom,(c_Type_Otyping(c_Type_Oshift(A,B,C,tc_Type_Otype),c_Lambda_Olift(D,B),E)|~c_Type_Otyping(A,D,E))).
cnf(c_0_20,axiom,c_Type_Otyping(v_e____,v_u____,v_T____)).
