fof(c_0_43,conjecture,![A]:![B]:is_a_theorem(implies(A,implies(falsehood,B)))).
cnf(condensed_detachment,axiom,(is_a_theorem(A)|~is_a_theorem(implies(B,A))|~is_a_theorem(B))).
cnf(c0_6,axiom,is_a_theorem(implies(implies(A,implies(B,C)),implies(implies(A,B),implies(A,C))))).
cnf(c0_2,axiom,is_a_theorem(implies(A,implies(B,A)))).
cnf(c0_5,axiom,is_a_theorem(implies(implies(implies(A,falsehood),falsehood),A))).
cnf(c_0_5,axiom,(is_a_theorem(A)|~is_a_theorem(implies(B,A))|~is_a_theorem(B))).
cnf(c_0_6,axiom,is_a_theorem(implies(implies(A,implies(B,C)),implies(implies(A,B),implies(A,C))))).
cnf(c_0_9,axiom,is_a_theorem(implies(A,implies(B,A)))).
cnf(c_0_33,axiom,is_a_theorem(implies(implies(implies(A,falsehood),falsehood),A))).
