fof(c_0_22,conjecture,hBOOL(hAPP(c_InductTermi_OIT,v_ta____))).
cnf(cls_set__takeWhileD_1,axiom,(hBOOL(hAPP(A,B))|~c_in(B,c_List_Oset(c_List_OtakeWhile(A,C,D),D),D))).
cnf(cls_in__listsp__conv__set_1,axiom,(c_List_Olistsp(A,B,C)|c_in(c_List_Osko__List__Xin__listsp__conv__set__1__1(A,B,C),c_List_Oset(B,C),C))).
cnf(cls_in__listsp__conv__set_2,axiom,(c_List_Olistsp(A,B,C)|~hBOOL(hAPP(A,c_List_Osko__List__Xin__listsp__conv__set__1__1(A,B,C))))).
cnf(cls_takeWhile_Osimps_I2_J_0,axiom,(c_List_OtakeWhile(A,c_List_Olist_OCons(B,C,D),D)=c_List_Olist_OCons(B,c_List_OtakeWhile(A,C,D),D)|~hBOOL(hAPP(A,B)))).
cnf(cls_App_I4_J_0,axiom,hBOOL(hAPP(c_InductTermi_OIT,v_ta____))).
cnf(cls_takeWhile_Osimps_I1_J_0,axiom,c_List_OtakeWhile(A,c_List_Olist_ONil(B),B)=c_List_Olist_ONil(B)).
cnf(cls_lifts__IT_0,axiom,(c_List_Olistsp(c_InductTermi_OIT,c_List_Omap(c_COMBC(c_Lambda_Olift,c_HOL_Ozero__class_Ozero(tc_nat),tc_Lambda_OdB,tc_nat,tc_Lambda_OdB),A,tc_Lambda_OdB,tc_Lambda_OdB),tc_Lambda_OdB)|~c_List_Olistsp(c_InductTermi_OIT,A,tc_Lambda_OdB))).
cnf(cls_map__eq__Cons__conv_3,axiom,c_List_Omap(A,c_List_Olist_OCons(B,C,D),D,E)=c_List_Olist_OCons(hAPP(A,B),c_List_Omap(A,C,D,E),E)).
cnf(cls_Nil__is__map__conv_1,axiom,c_List_Olist_ONil(A)=c_List_Omap(B,c_List_Olist_ONil(C),C,A)).
cnf(cls_COMBC__def_0,axiom,hAPP(c_COMBC(A,B,C,D,E),F)=hAPP(hAPP(A,F),B)).
cnf(c_0_11,axiom,(hBOOL(hAPP(A,B))|~c_in(B,c_List_Oset(c_List_OtakeWhile(A,C,D),D),D))).
cnf(c_0_12,axiom,(c_List_Olistsp(A,B,C)|c_in(c_List_Osko__List__Xin__listsp__conv__set__1__1(A,B,C),c_List_Oset(B,C),C))).
cnf(c_0_13,axiom,(c_List_Olistsp(A,B,C)|~hBOOL(hAPP(A,c_List_Osko__List__Xin__listsp__conv__set__1__1(A,B,C))))).
cnf(c_0_16,axiom,(c_List_OtakeWhile(A,c_List_Olist_OCons(B,C,D),D)=c_List_Olist_OCons(B,c_List_OtakeWhile(A,C,D),D)|~hBOOL(hAPP(A,B)))).
cnf(c_0_17,axiom,hBOOL(hAPP(c_InductTermi_OIT,v_ta____))).
cnf(c_0_27,axiom,c_List_OtakeWhile(A,c_List_Olist_ONil(B),B)=c_List_Olist_ONil(B)).
cnf(c_0_28,axiom,(c_List_Olistsp(c_InductTermi_OIT,c_List_Omap(c_COMBC(c_Lambda_Olift,c_HOL_Ozero__class_Ozero(tc_nat),tc_Lambda_OdB,tc_nat,tc_Lambda_OdB),A,tc_Lambda_OdB,tc_Lambda_OdB),tc_Lambda_OdB)|~c_List_Olistsp(c_InductTermi_OIT,A,tc_Lambda_OdB))).
cnf(c_0_32,axiom,c_List_Omap(A,c_List_Olist_OCons(B,C,D),D,E)=c_List_Olist_OCons(hAPP(A,B),c_List_Omap(A,C,D,E),E)).
cnf(c_0_33,axiom,c_List_Olist_ONil(A)=c_List_Omap(B,c_List_Olist_ONil(C),C,A)).
cnf(c_0_39,axiom,hAPP(c_COMBC(A,B,C,D,E),F)=hAPP(hAPP(A,F),B)).
