fof(c_0_15,conjecture,![A]:![B]:axiom(or(not(A),or(B,A)))).
cnf(rule_3,axiom,(theorem(or(not(A),B))|~axiom(or(not(A),C))|~theorem(or(not(C),B)))).
cnf(rule_1,axiom,(theorem(A)|~axiom(A))).
cnf(axiom_1_3,axiom,axiom(or(not(A),or(B,A)))).
cnf(rule_2,axiom,(theorem(A)|~axiom(or(not(B),A))|~theorem(B))).
cnf(axiom_1_4,axiom,axiom(or(not(or(A,B)),or(B,A)))).
cnf(axiom_1_2,axiom,axiom(or(not(or(A,A)),A))).
cnf(c_0_7,axiom,(theorem(or(not(A),B))|~axiom(or(not(A),C))|~theorem(or(not(C),B)))).
cnf(c_0_8,axiom,(theorem(A)|~axiom(A))).
cnf(c_0_11,axiom,axiom(or(not(A),or(B,A)))).
cnf(c_0_12,axiom,(theorem(A)|~axiom(or(not(B),A))|~theorem(B))).
cnf(c_0_13,axiom,axiom(or(not(or(A,B)),or(B,A)))).
cnf(c_0_16,axiom,axiom(or(not(or(A,A)),A))).
