fof(c_0_42,conjecture,![A]:![B]:![C]:is_a_theorem(implies(A,implies(implies(A,B),implies(C,B))))).
cnf(condensed_detachment,axiom,(is_a_theorem(A)|~is_a_theorem(implies(B,A))|~is_a_theorem(B))).
cnf(cn_19,axiom,is_a_theorem(implies(implies(implies(A,B),C),implies(B,C)))).
cnf(cn_59,axiom,is_a_theorem(implies(implies(not(A),B),implies(implies(C,B),implies(implies(A,C),B))))).
cnf(cn_37,axiom,is_a_theorem(implies(implies(implies(A,B),C),implies(not(A),C)))).
cnf(c_0_5,axiom,(is_a_theorem(A)|~is_a_theorem(implies(B,A))|~is_a_theorem(B))).
cnf(c_0_6,axiom,is_a_theorem(implies(implies(implies(A,B),C),implies(B,C)))).
cnf(c_0_7,axiom,is_a_theorem(implies(implies(not(A),B),implies(implies(C,B),implies(implies(A,C),B))))).
cnf(c_0_10,axiom,is_a_theorem(implies(implies(implies(A,B),C),implies(not(A),C)))).
