fof(c_0_24,conjecture,![A]:![B]:axiom(or(not(or(A,B)),or(B,A)))).
cnf(axiom_1_5,axiom,axiom(implies(or(A,or(B,C)),or(B,or(A,C))))).
cnf(implies_definition,axiom,implies(A,B)=or(not(A),B)).
cnf(rule_2,axiom,(theorem(A)|~theorem(implies(B,A))|~theorem(B))).
cnf(rule_1,axiom,(theorem(A)|~axiom(A))).
cnf(axiom_1_4,axiom,axiom(implies(or(A,B),or(B,A)))).
cnf(equivalent_defn,axiom,equivalent(A,B)=and(implies(A,B),implies(B,A))).
cnf(and_defn,axiom,and(A,B)=not(or(not(A),not(B)))).
cnf(c_0_8,axiom,axiom(implies(or(A,or(B,C)),or(B,or(A,C))))).
cnf(c_0_9,axiom,implies(A,B)=or(not(A),B)).
cnf(c_0_10,axiom,(theorem(A)|~theorem(implies(B,A))|~theorem(B))).
cnf(c_0_11,axiom,(theorem(A)|~axiom(A))).
cnf(c_0_13,axiom,axiom(implies(or(A,B),or(B,A)))).
cnf(c_0_25,axiom,equivalent(A,B)=and(implies(A,B),implies(B,A))).
cnf(c_0_26,axiom,and(A,B)=not(or(not(A),not(B)))).
