fof(c_0_58,conjecture,![A]:![B]:![C]:![D]:c_in(A,c_PropLog_Othms(c_insert(c_PropLog_Opl_Oop_A_N_62(c_PropLog_Opl_Oop_A_N_62(A,B,C),c_PropLog_Opl_Ofalse,C),D,tc_PropLog_Opl(C)),C),tc_PropLog_Opl(C))).
cnf(cls_PropLog_Othms_OH_0,axiom,(c_in(A,c_PropLog_Othms(B,C),tc_PropLog_Opl(C))|~c_in(A,B,tc_PropLog_Opl(C)))).
cnf(cls_Set_OinsertCI_1,axiom,c_in(A,c_insert(A,B,C),C)).
cnf(cls_Set_OinsertCI_0,axiom,(c_in(A,c_insert(B,C,D),D)|~c_in(A,C,D))).
cnf(cls_PropLog_Othms_OMP_0,axiom,(c_in(A,c_PropLog_Othms(B,C),tc_PropLog_Opl(C))|~c_in(D,c_PropLog_Othms(B,C),tc_PropLog_Opl(C))|~c_in(c_PropLog_Opl_Oop_A_N_62(D,A,C),c_PropLog_Othms(B,C),tc_PropLog_Opl(C)))).
cnf(cls_PropLog_Odeduction_0,axiom,(c_in(c_PropLog_Opl_Oop_A_N_62(A,B,C),c_PropLog_Othms(D,C),tc_PropLog_Opl(C))|~c_in(B,c_PropLog_Othms(c_insert(A,D,tc_PropLog_Opl(C)),C),tc_PropLog_Opl(C)))).
cnf(cls_PropLog_Othms_ODN_0,axiom,c_in(c_PropLog_Opl_Oop_A_N_62(c_PropLog_Opl_Oop_A_N_62(c_PropLog_Opl_Oop_A_N_62(A,c_PropLog_Opl_Ofalse,B),c_PropLog_Opl_Ofalse,B),A,B),c_PropLog_Othms(C,B),tc_PropLog_Opl(B))).
cnf(c_0_7,axiom,(c_in(A,c_PropLog_Othms(B,C),tc_PropLog_Opl(C))|~c_in(A,B,tc_PropLog_Opl(C)))).
cnf(c_0_8,axiom,c_in(A,c_insert(A,B,C),C)).
cnf(c_0_9,axiom,(c_in(A,c_insert(B,C,D),D)|~c_in(A,C,D))).
cnf(c_0_10,axiom,(c_in(A,c_PropLog_Othms(B,C),tc_PropLog_Opl(C))|~c_in(D,c_PropLog_Othms(B,C),tc_PropLog_Opl(C))|~c_in(c_PropLog_Opl_Oop_A_N_62(D,A,C),c_PropLog_Othms(B,C),tc_PropLog_Opl(C)))).
cnf(c_0_18,axiom,(c_in(c_PropLog_Opl_Oop_A_N_62(A,B,C),c_PropLog_Othms(D,C),tc_PropLog_Opl(C))|~c_in(B,c_PropLog_Othms(c_insert(A,D,tc_PropLog_Opl(C)),C),tc_PropLog_Opl(C)))).
cnf(c_0_27,axiom,c_in(c_PropLog_Opl_Oop_A_N_62(c_PropLog_Opl_Oop_A_N_62(c_PropLog_Opl_Oop_A_N_62(A,c_PropLog_Opl_Ofalse,B),c_PropLog_Opl_Ofalse,B),A,B),c_PropLog_Othms(C,B),tc_PropLog_Opl(B))).
