fof(c_0_19,conjecture,![A]:![B]:(A xor truth xor B)=(A xor (truth xor B))).
cnf(implies_definition,axiom,implies(A,B)=(truth xor and_star(A,truth xor B))).
cnf(axiom_4,axiom,and_star(A,truth)=A).
cnf(and_star_commutativity,axiom,and_star(A,B)=and_star(B,A)).
cnf(axiom_7,axiom,(A xor (truth xor B))=(A xor truth xor B)).
cnf(axiom_3,axiom,(A xor A)=falsehood).
cnf(axiom_2,axiom,(A xor falsehood)=A).
cnf(xor_commutativity,axiom,(A xor B)=(B xor A)).
cnf(c_0_9,axiom,implies(A,B)=(truth xor and_star(A,truth xor B))).
cnf(c_0_10,axiom,and_star(A,truth)=A).
cnf(c_0_11,axiom,and_star(A,B)=and_star(B,A)).
cnf(c_0_12,axiom,(A xor (truth xor B))=(A xor truth xor B)).
cnf(c_0_13,axiom,(A xor A)=falsehood).
cnf(c_0_14,axiom,(A xor falsehood)=A).
cnf(c_0_15,axiom,(A xor B)=(B xor A)).
