fof(c_0_47,conjecture,![A]:![B]:![C]:![D]:is_a_theorem(equivalent(equivalent(equivalent(A,equivalent(B,C)),equivalent(A,equivalent(equivalent(C,B),D))),D))).
cnf(condensed_detachment,axiom,(is_a_theorem(A)|~is_a_theorem(equivalent(B,A))|~is_a_theorem(B))).
cnf(lg_2,axiom,is_a_theorem(equivalent(equivalent(equivalent(equivalent(equivalent(A,B),equivalent(A,C)),equivalent(B,C)),D),D))).
cnf(lg_4,axiom,is_a_theorem(equivalent(equivalent(equivalent(equivalent(A,B),C),D),equivalent(equivalent(equivalent(A,E),C),equivalent(equivalent(B,E),D))))).
cnf(lg_3,axiom,is_a_theorem(equivalent(equivalent(equivalent(equivalent(equivalent(equivalent(A,B),equivalent(A,C)),D),equivalent(equivalent(B,C),D)),E),E))).
cnf(c_0_5,axiom,(is_a_theorem(A)|~is_a_theorem(equivalent(B,A))|~is_a_theorem(B))).
cnf(c_0_6,axiom,is_a_theorem(equivalent(equivalent(equivalent(equivalent(equivalent(A,B),equivalent(A,C)),equivalent(B,C)),D),D))).
cnf(c_0_7,axiom,is_a_theorem(equivalent(equivalent(equivalent(equivalent(A,B),C),D),equivalent(equivalent(equivalent(A,E),C),equivalent(equivalent(B,E),D))))).
cnf(c_0_17,axiom,is_a_theorem(equivalent(equivalent(equivalent(equivalent(equivalent(equivalent(A,B),equivalent(A,C)),D),equivalent(equivalent(B,C),D)),E),E))).
