fof(c_0_11,conjecture,![A]:![B]:(is_a_theorem(A)|~is_a_theorem(implies(implies(A,B),A)))).
cnf(condensed_detachment,axiom,(is_a_theorem(A)|~is_a_theorem(implies(B,A))|~is_a_theorem(B))).
cnf(c0_3,axiom,is_a_theorem(implies(implies(implies(A,B),A),A))).
cnf(c0_1,axiom,is_a_theorem(implies(implies(A,B),implies(implies(B,C),implies(A,C))))).
cnf(c0_2,axiom,is_a_theorem(implies(A,implies(B,A)))).
cnf(c_0_5,axiom,(is_a_theorem(A)|~is_a_theorem(implies(B,A))|~is_a_theorem(B))).
cnf(c_0_6,axiom,is_a_theorem(implies(implies(implies(A,B),A),A))).
cnf(c_0_7,axiom,is_a_theorem(implies(implies(A,B),implies(implies(B,C),implies(A,C))))).
cnf(c_0_13,axiom,is_a_theorem(implies(A,implies(B,A)))).
