fof(c_0_38,conjecture,![A]:![B]:![C]:and_star(and_star(A,B),C)=and_star(A,and_star(B,C))).
cnf(and_star_commutativity,axiom,and_star(A,B)=and_star(B,A)).
cnf(axiom_6,axiom,and_star(truth xor A,A)=falsehood).
cnf(xor_commutativity,axiom,(A xor B)=(B xor A)).
cnf(implies_definition,axiom,implies(A,B)=(truth xor and_star(A,truth xor B))).
cnf(axiom_4,axiom,and_star(A,truth)=A).
cnf(axiom_5,axiom,and_star(A,falsehood)=falsehood).
cnf(and_star_associativity,axiom,and_star(and_star(A,B),C)=and_star(A,and_star(B,C))).
cnf(axiom_8,axiom,and_star(and_star(truth xor A,B)xor truth,B)=and_star(and_star(truth xor B,A)xor truth,A)).
cnf(axiom_3,axiom,(A xor A)=falsehood).
cnf(axiom_2,axiom,(A xor falsehood)=A).
cnf(c_0_11,axiom,and_star(A,B)=and_star(B,A)).
cnf(c_0_12,axiom,and_star(truth xor A,A)=falsehood).
cnf(c_0_14,axiom,(A xor B)=(B xor A)).
cnf(c_0_16,axiom,implies(A,B)=(truth xor and_star(A,truth xor B))).
cnf(c_0_17,axiom,and_star(A,truth)=A).
cnf(c_0_18,axiom,and_star(A,falsehood)=falsehood).
cnf(c_0_19,axiom,and_star(and_star(A,B),C)=and_star(A,and_star(B,C))).
cnf(c_0_22,axiom,and_star(and_star(truth xor A,B)xor truth,B)=and_star(and_star(truth xor B,A)xor truth,A)).
cnf(c_0_26,axiom,(A xor A)=falsehood).
cnf(c_0_28,axiom,(A xor falsehood)=A).
