fof(c_0_20,conjecture,![A]:![B]:![C]:![D]:is_a_theorem(implies(implies(A,implies(B,C)),implies(implies(implies(D,B),A),implies(B,C))))).
cnf(condensed_detachment,axiom,(is_a_theorem(A)|~is_a_theorem(implies(B,A))|~is_a_theorem(B))).
cnf(cn_60,axiom,is_a_theorem(implies(implies(A,implies(not(B),C)),implies(A,implies(implies(D,C),implies(implies(B,D),C)))))).
cnf(cn_37,axiom,is_a_theorem(implies(implies(implies(A,B),C),implies(not(A),C)))).
cnf(cn_19,axiom,is_a_theorem(implies(implies(implies(A,B),C),implies(B,C)))).
cnf(c_0_5,axiom,(is_a_theorem(A)|~is_a_theorem(implies(B,A))|~is_a_theorem(B))).
cnf(c_0_6,axiom,is_a_theorem(implies(implies(A,implies(not(B),C)),implies(A,implies(implies(D,C),implies(implies(B,D),C)))))).
cnf(c_0_11,axiom,is_a_theorem(implies(implies(implies(A,B),C),implies(not(A),C)))).
cnf(c_0_14,axiom,is_a_theorem(implies(implies(implies(A,B),C),implies(B,C)))).
