fof(c_0_27,conjecture,![A]:![B]:![C]:(theorem(or(not(or(A,B)),or(A,C)))|~theorem(or(not(B),C)))).
cnf(rule_2,axiom,(theorem(A)|~theorem(implies(B,A))|~theorem(B))).
cnf(implies_definition,axiom,implies(A,B)=or(not(A),B)).
cnf(rule_1,axiom,(theorem(A)|~axiom(A))).
cnf(axiom_1_6,axiom,axiom(implies(implies(A,B),implies(or(C,A),or(C,B))))).
cnf(axiom_1_5,axiom,axiom(implies(or(A,or(B,C)),or(B,or(A,C))))).
cnf(axiom_1_3,axiom,axiom(implies(A,or(B,A)))).
cnf(axiom_1_2,axiom,axiom(implies(or(A,A),A))).
cnf(axiom_1_4,axiom,axiom(implies(or(A,B),or(B,A)))).
cnf(c_0_9,axiom,(theorem(A)|~theorem(implies(B,A))|~theorem(B))).
cnf(c_0_10,axiom,implies(A,B)=or(not(A),B)).
cnf(c_0_12,axiom,(theorem(A)|~axiom(A))).
cnf(c_0_13,axiom,axiom(implies(implies(A,B),implies(or(C,A),or(C,B))))).
cnf(c_0_14,axiom,axiom(implies(or(A,or(B,C)),or(B,or(A,C))))).
cnf(c_0_15,axiom,axiom(implies(A,or(B,A)))).
cnf(c_0_19,axiom,axiom(implies(or(A,A),A))).
cnf(c_0_28,axiom,axiom(implies(or(A,B),or(B,A)))).
