fof(c_0_23,conjecture,![A]:![B]:![C]:(c_in(A,c_PropLog_Othms(B,C),tc_PropLog_Opl(C))|~c_in(A,B,tc_PropLog_Opl(C)))).
cnf(cls_PropLog_Osat__imp_0,axiom,(c_PropLog_Osat(A,c_PropLog_Opl_Oop_A_N_62(B,C,D),D)|~c_PropLog_Osat(c_insert(B,A,tc_PropLog_Opl(D)),C,D))).
cnf(cls_PropLog_Oweaken__left__insert_0,axiom,(c_in(A,c_PropLog_Othms(c_insert(B,C,tc_PropLog_Opl(D)),D),tc_PropLog_Opl(D))|~c_in(A,c_PropLog_Othms(C,D),tc_PropLog_Opl(D)))).
cnf(cls_PropLog_Othms_OMP_0,axiom,(c_in(A,c_PropLog_Othms(B,C),tc_PropLog_Opl(C))|~c_in(D,c_PropLog_Othms(B,C),tc_PropLog_Opl(C))|~c_in(c_PropLog_Opl_Oop_A_N_62(D,A,C),c_PropLog_Othms(B,C),tc_PropLog_Opl(C)))).
cnf(cls_PropLog_Othms_OH_0,axiom,(c_in(A,c_PropLog_Othms(B,C),tc_PropLog_Opl(C))|~c_in(A,B,tc_PropLog_Opl(C)))).
cnf(cls_Set_OinsertCI_1,axiom,c_in(A,c_insert(A,B,C),C)).
cnf(c_0_8,axiom,(c_PropLog_Osat(A,c_PropLog_Opl_Oop_A_N_62(B,C,D),D)|~c_PropLog_Osat(c_insert(B,A,tc_PropLog_Opl(D)),C,D))).
cnf(c_0_13,axiom,(c_in(A,c_PropLog_Othms(c_insert(B,C,tc_PropLog_Opl(D)),D),tc_PropLog_Opl(D))|~c_in(A,c_PropLog_Othms(C,D),tc_PropLog_Opl(D)))).
cnf(c_0_16,axiom,(c_in(A,c_PropLog_Othms(B,C),tc_PropLog_Opl(C))|~c_in(D,c_PropLog_Othms(B,C),tc_PropLog_Opl(C))|~c_in(c_PropLog_Opl_Oop_A_N_62(D,A,C),c_PropLog_Othms(B,C),tc_PropLog_Opl(C)))).
cnf(c_0_19,axiom,(c_in(A,c_PropLog_Othms(B,C),tc_PropLog_Opl(C))|~c_in(A,B,tc_PropLog_Opl(C)))).
cnf(c_0_20,axiom,c_in(A,c_insert(A,B,C),C)).
