fof(c_0_9,conjecture,hAPP(hAPP(c_Type_Otype_OFun,v_T_H_H____),c_List_Ofoldr(c_Type_Otype_OFun,v_Ts____,v_T_H____,tc_Type_Otype,tc_Type_Otype))=v_T____).
cnf(cls_App_0,axiom,(c_Type_Otyping(A,hAPP(hAPP(c_Lambda_OdB_OApp,B),C),D)|~c_Type_Otyping(A,C,E)|~c_Type_Otyping(A,B,hAPP(hAPP(c_Type_Otype_OFun,E),D)))).
cnf(cls_T_0,axiom,v_T____=hAPP(hAPP(c_Type_Otype_OFun,v_T_H_H____),c_List_Ofoldr(c_Type_Otype_OFun,v_Ts____,v_T_H____,tc_Type_Otype,tc_Type_Otype))).
cnf(cls_uT_0,axiom,c_Type_Otyping(v_e____,v_u____,v_T____)).
cnf(cls_CHAINED_0,axiom,c_Type_Otyping(v_e____,c_Lambda_Osubst(v_a____,v_u____,v_i____),v_T_H_H____)).
cnf(c_0_5,axiom,(c_Type_Otyping(A,hAPP(hAPP(c_Lambda_OdB_OApp,B),C),D)|~c_Type_Otyping(A,C,E)|~c_Type_Otyping(A,B,hAPP(hAPP(c_Type_Otype_OFun,E),D)))).
cnf(c_0_6,axiom,v_T____=hAPP(hAPP(c_Type_Otype_OFun,v_T_H_H____),c_List_Ofoldr(c_Type_Otype_OFun,v_Ts____,v_T_H____,tc_Type_Otype,tc_Type_Otype))).
cnf(c_0_10,axiom,c_Type_Otyping(v_e____,v_u____,v_T____)).
cnf(c_0_11,axiom,c_Type_Otyping(v_e____,c_Lambda_Osubst(v_a____,v_u____,v_i____),v_T_H_H____)).
