fof(c_0_12,conjecture,![A]:![B]:(theorem(A)|~theorem(B)|~theorem(or(not(B),A)))).
cnf(rule_2,axiom,(theorem(A)|~theorem(implies(B,A))|~theorem(B))).
cnf(implies_definition,axiom,implies(A,B)=or(not(A),B)).
cnf(rule_1,axiom,(theorem(A)|~axiom(A))).
cnf(axiom_1_6,axiom,axiom(implies(implies(A,B),implies(or(C,A),or(C,B))))).
cnf(axiom_1_4,axiom,axiom(implies(or(A,B),or(B,A)))).
cnf(c_0_6,axiom,(theorem(A)|~theorem(implies(B,A))|~theorem(B))).
cnf(c_0_7,axiom,implies(A,B)=or(not(A),B)).
cnf(c_0_9,axiom,(theorem(A)|~axiom(A))).
cnf(c_0_10,axiom,axiom(implies(implies(A,B),implies(or(C,A),or(C,B))))).
cnf(c_0_18,axiom,axiom(implies(or(A,B),or(B,A)))).
