fof(c_0_15,conjecture,![A]:![B]:implies(implies(not(A),not(B)),implies(B,A))=truth).
cnf(or_commutativity,axiom,or(A,B)=or(B,A)).
cnf(or_definition,axiom,or(A,B)=implies(not(A),B)).
cnf(wajsberg_4,axiom,implies(implies(not(A),not(B)),implies(B,A))=truth).
cnf(wajsberg_1,axiom,implies(truth,A)=A).
cnf(false_definition,axiom,not(truth)=falsehood).
cnf(wajsberg_3,axiom,implies(implies(A,B),B)=implies(implies(B,A),A)).
cnf(and_definition,axiom,and(A,B)=not(or(not(A),not(B)))).
cnf(xor_definition,axiom,(A xor B)=or(and(A,not(B)),and(not(A),B))).
cnf(c_0_9,axiom,or(A,B)=or(B,A)).
cnf(c_0_10,axiom,or(A,B)=implies(not(A),B)).
cnf(c_0_11,axiom,implies(implies(not(A),not(B)),implies(B,A))=truth).
cnf(c_0_12,axiom,implies(truth,A)=A).
cnf(c_0_13,axiom,not(truth)=falsehood).
cnf(c_0_18,axiom,implies(implies(A,B),B)=implies(implies(B,A),A)).
cnf(c_0_20,axiom,and(A,B)=not(or(not(A),not(B)))).
cnf(c_0_24,axiom,(A xor B)=or(and(A,not(B)),and(not(A),B))).
