fof(c_0_16,conjecture,![A]:![B]:is_a_theorem(implies(A,implies(B,A)))).
cnf(condensed_detachment,axiom,(is_a_theorem(A)|~is_a_theorem(implies(B,A))|~is_a_theorem(B))).
cnf(cn_54,axiom,is_a_theorem(implies(implies(A,B),implies(implies(not(A),B),B)))).
cnf(cn_3,axiom,is_a_theorem(implies(A,implies(not(A),B)))).
cnf(cn_18,axiom,is_a_theorem(implies(A,implies(B,A)))).
cnf(c_0_5,axiom,(is_a_theorem(A)|~is_a_theorem(implies(B,A))|~is_a_theorem(B))).
cnf(c_0_6,axiom,is_a_theorem(implies(implies(A,B),implies(implies(not(A),B),B)))).
cnf(c_0_10,axiom,is_a_theorem(implies(A,implies(not(A),B)))).
cnf(c_0_13,axiom,is_a_theorem(implies(A,implies(B,A)))).
